"""Build Phase 8/9/11 statutory rule candidate reports.

Inserts clause rows (idempotent) and writes extraction report JSONs to
/app/reports/ for Transfer of Land Act 1893, Building Regulations 2012,
Strata Titles Act 1985. All quotes transcribed verbatim from the official
consolidated PDFs stored in /app/data/raw-sources/.
"""
import os
import json
import uuid
import psycopg

DB = os.environ["DATABASE_URL"].replace(
    "postgresql+asyncpg://", "postgresql://"
).replace("postgresql+psycopg://", "postgresql://")

SV_TLA = "f4c5a48c-b589-4617-bb82-2853d52131bd"
SV_BR = "ccddad06-71b2-43e7-b2af-26ddc1128793"
SV_STA = "2d895468-390d-410b-bd98-2e3bed0c27d2"

EXTRACTOR = "manual_statutory_codification:v1"

conn = psycopg.connect(DB)
cur = conn.cursor()


def ensure_clause(sv_id, key, title, section_ref, text):
    cur.execute(
        """INSERT INTO clauses
           (id, source_version_id, clause_key, clause_type, title, section_ref,
            disposition, text, quote, parser_name, parser_version,
            metadata_json, created_at, updated_at)
           VALUES (%s, %s, %s, 'section', %s, %s, 'rule_bearing', %s, %s,
                   'manual_statutory_codification', 'v1', '{}', now(), now())
           ON CONFLICT ON CONSTRAINT uq_clauses_version_key DO NOTHING""",
        (str(uuid.uuid4()), sv_id, key, title, section_ref, text, text),
    )
    cur.execute(
        "SELECT id FROM clauses WHERE source_version_id = %s AND clause_key = %s",
        (sv_id, key),
    )
    return str(cur.fetchone()[0])


def cand(sv_id, clause_ids, clause_key, rule_key, quote, section, ref,
         operator=None, value=None, unit=None, condition=None,
         check_type="boolean_presence", evaluable="yes",
         rule_type="requirement", canonical=None):
    vj = {"value": value} if value is not None else {"base_rule_key": canonical or rule_key}
    return {
        "rule_key": rule_key,
        "canonical_rule_key": canonical or rule_key,
        "rule_type": rule_type,
        "pathway": "none",
        "dwelling_type": None,
        "applicable_r_codes": None,
        "applicable_zones": None,
        "council_scope": None,
        "operator": operator,
        "value_json": vj,
        "unit": unit,
        "condition_json": condition or {},
        "quote": quote,
        "instrument_section": section,
        "table_reference": ref,
        "effective_from": None,
        "effective_to": None,
        "source_version_id": sv_id,
        "clause_id": clause_ids[clause_key],
        "extractor_model": EXTRACTOR,
        "check_type": check_type,
        "evaluable": evaluable,
    }


reports = {}

# =====================================================================
# PHASE 8 - Transfer of Land Act 1893 (as at 25 Sep 2025)
# =====================================================================
tla_clauses = {}
tla_clause_defs = [
    ("s137", "Lodging caveats for land already under this Act", "s. 137",
     "Any beneficiary or other person claiming any estate or interest in land under the operation of this Act or in any lease mortgage or charge under any unregistered instrument document or writing or under any equitable mortgage or charge by deposit without writing or by devolution in law or otherwise may lodge a caveat with the Registrar in an approved form."),
    ("s138", "Consequences of lodging caveat", "s. 138",
     "Except in the case of a caveat lodged by or on behalf of a beneficiary claiming under any will or settlement or by the Registrar pursuant to the direction of the Commissioner every caveat lodged against a proprietor shall be deemed to have lapsed as to the land affected by the transfer or other dealing upon the expiration of 14 days after notice served on the caveator."),
    ("s138B", "Requiring caveator to seek court order extending s. 138A caveat", "s. 138B",
     "If the notice referred to in subsection (1) is served on the caveator then the caveat lapses 21 days after the day on which the notice was served unless, before that time, the caveator has obtained from the Supreme Court an order extending the operation of the caveat and lodged with the Registrar a copy of the order."),
    ("s138C", "Supreme Court's powers on application by caveator", "s. 138C",
     "On the hearing of an application under subsection (1), the Supreme Court, if satisfied that the caveator's claim has or may have substance, may make an order extending the operation of the caveat for such period as is specified in the order or until the further order of the court; and if not satisfied that the caveator's claim has or may have substance, shall dismiss the application."),
    ("s138D", "Restrictions on caveators lodging further s. 138A caveats", "s. 138D",
     "the caveator cannot lodge with the Registrar any further section 138A caveat in respect of the same land unless the consent of the proprietor to do so and, if the notice issued under section 138B(1) was issued on the application of a judgment creditor, the consent of the judgment creditor to do so are endorsed on the further caveat; or the Supreme Court has made an order giving leave for the lodgment of the further caveat and a copy of that order has been served on the Registrar."),
    ("s139", "Effect of caveats", "s. 139",
     "While any caveat shall remain in force prohibiting any registration or dealing the Registrar shall not enter in the Register any change in the proprietorship of or any transfer or other instrument purporting to transfer or otherwise deal with or affect the estate or interest in respect to which such caveat may be lodged."),
    ("s140", "Compensation for caveat lodged without reasonable cause", "s. 140",
     "Any person lodging any caveat with the Registrar either against bringing land under this Act or otherwise without reasonable cause shall be liable to make to any person who may have sustained damage thereby such compensation as a judge on a summons in chambers shall deem just and order."),
    ("s141", "Registrar's duties when caveat lodged or lapses", "s. 141",
     "Where a caveat is lodged under section 137; or a caveat lapses, whether because of the effect of a provision of this Act or the operation of an order of the Supreme Court, the Registrar shall enter a memorandum of the caveat or the lapse of the caveat, as the case requires, on the certificate of title for the land in respect of which the caveat was lodged."),
    ("s129B", "Discharge and modification of restrictive covenants", "s. 129B",
     "any covenant or agreement affecting or restricting the use of land may be discharged or modified by agreement by all persons interested in the land affected by such covenant or agreement consenting to such discharge or modification. The Commissioner shall, when satisfied that all parties interested as aforesaid have agreed to the discharge or modification of any covenant entered on any certificate of title in the Register, direct the Registrar to enter a memorandum of the discharge or modification on each such certificate."),
    ("s129BA", "Restrictive covenants benefiting local governments and public authorities", "s. 129BA",
     "A restrictive covenant may, under this section, be created and made binding in respect of land under the operation of this Act for the benefit of the local government in whose district the land is situated; or a public authority, notwithstanding that the benefit of the restrictive covenant would not be in respect of land. A restrictive covenant under this section shall be in an instrument in an approved form that is lodged with the Registrar and accompanied by the written consent of each person who has a registered interest in any land that would be burdened by the restrictive covenant; and the prescribed fee."),
    ("s136C", "Notation of easements on subdivision plans", "s. 136C",
     "A proprietor of land that is a subject of a plan may note, in an approved form, on the plan the location of an easement to which the land is proposed to be subject. An easement cannot be noted on a plan unless the land to be burdened by the easement is a subject of the plan but any land to be benefited by the easement need not be a subject of the plan. An easement for the benefit of the local government in whose district the land is situated; or a public authority, may be noted on a plan under this section notwithstanding that the benefit of the easement would not be in respect of land."),
    ("s106", "Mortgage or charge not to operate as transfer; default procedures", "s. 106",
     "a mortgage and a charge under this Act shall when registered as hereinbefore provided have effect as a security but shall not operate as a transfer of the land thereby mortgaged or charged; and in case default be made in payment of the principal sum interest or annuity secured or any part thereof respectively or in the performance or observance of any covenant expressed in any mortgage or charge or hereby declared to be implied in any mortgage and such default be continued for one month or for such other period of time as may therein for that purpose be expressly fixed the mortgagee or annuitant or his transferees may serve on the mortgagor or grantor or his transferees notice in writing to pay the money owing on such mortgage or charge or to perform and observe the aforesaid covenants (as the case may be)."),
    ("s61", "Effect of insertion of words \"no survivorship\"", "s. 61",
     "In every case after such words shall have been signed by the Registrar whether under this or any preceding section it shall not be lawful for any persons other than the proprietors registered to transfer or otherwise deal with the property without the order of the Supreme Court or a judge thereof obtained on motion or petition or the order of the Commissioner."),
    ("s227", "Survivor of joint proprietors may apply to be registered", "s. 227",
     "Upon the death of any person registered with any other person as joint proprietor of any land or of any lease or charge or as joint proprietor of any mortgage owned on a joint account in equity the Commissioner on the application of the person entitled and proof to his satisfaction of such events as aforesaid may direct the Registrar to register such applicant as the proprietor thereof."),
    ("s219", "Person entitled under will etc. may apply to be registered", "s. 219",
     "A devisee or person claiming any estate of freehold in possession or a power to appoint transfer or dispose of the same on a transmission may make application in writing to the Commissioner to be registered as proprietor thereof and shall produce the will or an office copy or probate of the will of the deceased proprietor or letters of administration with his will annexed or the letters of administration in case of intestacy or the settlement under which such applicant claims."),
    ("s220", "Application under s. 219, how dealt with", "s. 220",
     "the Commissioner may either reject such application altogether or direct notice thereof to be published once at least in one newspaper published in the city of Perth or circulating in the neighbourhood of the land and such further publicity to be given to such application as he may deem fit; and the Commissioner shall appoint a time not less than 14 days from the advertisement or the first of such advertisements if more than one upon or after which the Registrar shall unless a caveat shall be lodged forbidding the same register such applicant as the proprietor of such land."),
]
for key, title, ref, text in tla_clause_defs:
    tla_clauses[key] = ensure_clause(SV_TLA, key, title, ref, text)

TLA_PART_V = "Part V — Caveats"
TLA_PART_IV = "Part IV — Dealings with land"
TLA_PART_IVA = "Part IVA — Creation of easements and restrictive covenants by notations on subdivision plans and diagrams"
TLA_PART_XIV = "Part XIV — Miscellaneous"

tla_candidates = [
    cand(SV_TLA, tla_clauses, "s137", "tla_caveat_lodgement_standing",
         "Any beneficiary or other person claiming any estate or interest in land under the operation of this Act or in any lease mortgage or charge under any unregistered instrument document or writing or under any equitable mortgage or charge by deposit without writing or by devolution in law or otherwise may lodge a caveat with the Registrar in an approved form forbidding the registration of any person as transferee or proprietor.",
         TLA_PART_V, "s. 137(1)",
         condition={"verification": "caveator must claim an estate or interest in the land, lease, mortgage or charge"}),
    cand(SV_TLA, tla_clauses, "s137", "tla_caveat_form_signature_address",
         "Every such caveat shall state the name and address of the person by whom or on whose behalf the same is lodged and (except in case of a caveat lodged by order of the Supreme Court or by the Registrar pursuant to the direction of the Commissioner as hereinafter provided) shall be signed by the caveator or by his agent.",
         TLA_PART_V, "s. 137(1A)",
         condition={"verification": "caveat states caveator name and address and is signed"}),
    cand(SV_TLA, tla_clauses, "s137", "tla_caveat_service_address_required",
         "A caveat under this section cannot be lodged unless one of the following is specified in it for the purposes of the service of notices in relation to the caveat — (a) an address in Australia; (c) a way of receiving notices electronically (for example, an email address) that is prescribed by the regulations for the purposes of this paragraph.",
         TLA_PART_V, "s. 137(1D)",
         condition={"verification": "caveat specifies Australian address or prescribed electronic notice method"}),
    cand(SV_TLA, tla_clauses, "s137", "tla_caveat_statutory_declaration_max_days",
         "The person lodging such caveat shall if required by the Registrar support the same by statutory declaration stating the nature of the estate or interest claimed and the title thereto ... If such declaration when required by the Registrar be not lodged with him within 7 days from the date of such requisition the caveat shall be absolutely null and void.",
         TLA_PART_V, "s. 137(1B)-(1C)",
         operator="lte", value=7, unit="days", check_type="max_value",
         condition={"trigger": "Registrar requisition of statutory declaration", "consequence": "caveat absolutely null and void"}),
    cand(SV_TLA, tla_clauses, "s138", "tla_caveat_lapse_after_notice_days",
         "Except in the case of a caveat lodged by or on behalf of a beneficiary claiming under any will or settlement or by the Registrar pursuant to the direction of the Commissioner every caveat lodged against a proprietor shall be deemed to have lapsed as to the land affected by the transfer or other dealing upon the expiration of 14 days after notice served on the caveator that such proprietor has applied for the registration of a transfer or other dealing unless in the meantime such application is withdrawn.",
         TLA_PART_V, "s. 138(3)",
         operator="lte", value=14, unit="days", check_type="max_value",
         condition={"trigger": "notice served on caveator of application for registration", "exception": "caveat by beneficiary under will or settlement, or by Registrar on Commissioner's direction"}),
    cand(SV_TLA, tla_clauses, "s138B", "tla_caveat_21_day_lapse_without_court_order",
         "If the notice referred to in subsection (1) is served on the caveator then the caveat lapses 21 days after the day on which the notice was served unless, before that time, the caveator has — (a) obtained from the Supreme Court an order extending the operation of the caveat — (i) for such further period as is specified in the order; or (ii) until the further order of the court; and (b) lodged with the Registrar a copy of the order.",
         TLA_PART_V, "s. 138B(2)",
         operator="lte", value=21, unit="days", check_type="max_value",
         condition={"trigger": "service of Registrar's notice on caveator (s. 138B(1))", "applies_to": "section 138A caveats"}),
    cand(SV_TLA, tla_clauses, "s138C", "tla_caveat_court_extension_substance",
         "On the hearing of an application under subsection (1), the Supreme Court — (a) if satisfied that the caveator's claim has or may have substance — (i) may make an order extending the operation of the caveat for such period as is specified in the order; or (ii) may make an order extending the operation of the caveat until the further order of the court; and (b) if not satisfied that the caveator's claim has or may have substance, shall dismiss the application.",
         TLA_PART_V, "s. 138C(2)", check_type="conditional",
         condition={"verification": "Supreme Court extends caveat only if claim has or may have substance"}),
    cand(SV_TLA, tla_clauses, "s138D", "tla_caveat_no_further_caveat_same_land",
         "the caveator cannot lodge with the Registrar any further section 138A caveat in respect of the same land unless — (d) the consent of the proprietor to do so and, if the notice issued under section 138B(1) was issued on the application of a judgment creditor, the consent of the judgment creditor to do so are endorsed on the further caveat; or (e) the Supreme Court has made an order giving leave for the lodgment of the further caveat and a copy of that order has been served on the Registrar.",
         TLA_PART_V, "s. 138D(1)", check_type="conditional",
         condition={"trigger": "prior s. 138A caveat withdrawn after s. 138B(1) notice, lapsed, or lost effect by court order/dismissal"}),
    cand(SV_TLA, tla_clauses, "s139", "tla_caveat_blocks_registration",
         "While any caveat shall remain in force prohibiting any registration or dealing the Registrar shall not enter in the Register any change in the proprietorship of or any transfer or other instrument purporting to transfer or otherwise deal with or affect the estate or interest in respect to which such caveat may be lodged unless — (a) subsection (2) applies; or (b) the instrument is a property (seizure and sale) order within the meaning given in section 133; or (c) the instrument is a sheriff's dealing (within the meaning given in section 133) and the matter to which the caveat relates does not, under section 133(7), prevail against the dealing; or (d) section 142 applies.",
         TLA_PART_V, "s. 139(1)",
         condition={"verification": "title search shows no caveat in force before registering dealing"}),
    cand(SV_TLA, tla_clauses, "s140", "tla_caveat_compensation_without_reasonable_cause",
         "Any person lodging any caveat with the Registrar either against bringing land under this Act or otherwise without reasonable cause shall be liable to make to any person who may have sustained damage thereby such compensation as a judge on a summons in chambers shall deem just and order.",
         TLA_PART_V, "s. 140",
         condition={"verification": "caveat lodged with reasonable cause"}),
    cand(SV_TLA, tla_clauses, "s141", "tla_caveat_memorandum_on_title",
         "Where — (a) a caveat is lodged under section 137; or (b) a caveat lapses, whether because of the effect of a provision of this Act or the operation of an order of the Supreme Court, the Registrar shall enter a memorandum of the caveat or the lapse of the caveat, as the case requires, on the certificate of title for the land in respect of which the caveat was lodged.",
         TLA_PART_V, "s. 141(1)",
         condition={"verification": "memorandum of caveat or lapse appears on certificate of title"}),
    cand(SV_TLA, tla_clauses, "s129B", "tla_restrictive_covenant_discharge_agreement",
         "Notwithstanding anything contained in this Act to the contrary, but subject to subsection (3), any covenant or agreement affecting or restricting the use of land may be discharged or modified by agreement by all persons interested in the land affected by such covenant or agreement consenting to such discharge or modification. The Commissioner shall, when satisfied that all parties interested as aforesaid have agreed to the discharge or modification of any covenant entered on any certificate of title in the Register, direct the Registrar to enter a memorandum of the discharge or modification on each such certificate.",
         TLA_PART_IV, "s. 129B(1)-(2)", check_type="conditional",
         condition={"verification": "all persons interested consent; s. 129BA covenants follow s. 129BB; Part IVA covenants follow s. 136J"}),
    cand(SV_TLA, tla_clauses, "s129BA", "tla_restrictive_covenant_lg_public_authority",
         "A restrictive covenant may, under this section, be created and made binding in respect of land under the operation of this Act for the benefit of — (a) the local government in whose district the land is situated; or (b) a public authority, notwithstanding that the benefit of the restrictive covenant would not be in respect of land.",
         TLA_PART_IV, "s. 129BA(1)",
         condition={"verification": "covenant beneficiary is local government or public authority"}),
    cand(SV_TLA, tla_clauses, "s129BA", "tla_restrictive_covenant_lg_form_consent",
         "A restrictive covenant under this section shall be in an instrument in an approved form that is lodged with the Registrar and accompanied by — (a) the written consent of each person who has a registered interest in any land that would be burdened by the restrictive covenant; and (b) the prescribed fee.",
         TLA_PART_IV, "s. 129BA(2)",
         condition={"verification": "approved form instrument plus written consent of each registered interest holder"}),
    cand(SV_TLA, tla_clauses, "s136C", "tla_easement_notation_burdened_lot_on_plan",
         "An easement cannot be noted on a plan unless the land to be burdened by the easement is a subject of the plan but any land to be benefited by the easement need not be a subject of the plan.",
         TLA_PART_IVA, "s. 136C(2)",
         condition={"verification": "burdened land is a subject of the subdivision plan"}),
    cand(SV_TLA, tla_clauses, "s136C", "tla_easement_notation_lg_public_authority_benefit",
         "An easement for the benefit of — (a) the local government in whose district the land is situated; or (b) a public authority, may be noted on a plan under this section notwithstanding that the benefit of the easement would not be in respect of land.",
         TLA_PART_IVA, "s. 136C(3)",
         condition={"verification": "easement benefiting local government or public authority may be noted without benefited land"}),
    cand(SV_TLA, tla_clauses, "s136C", "tla_easement_notation_required_particulars",
         "The following information about the easement shall, subject to subsection (6), be specified in either the plan or in an instrument lodged in relation to the plan, or in both the plan and the instrument — (a) the land to be burdened by the easement; and (b) either — (i) the land to be benefited; or (ii) the name of the local government or the public authority to be benefited, by the easement, as the case may be; and (c) a description of the easement, whether by way of a short form, a modified or supplemented short form or in another manner.",
         TLA_PART_IVA, "s. 136C(5)",
         condition={"verification": "plan or instrument specifies burdened land, benefited land or authority, and easement description"}),
    cand(SV_TLA, tla_clauses, "s106", "tla_mortgage_operates_as_security_only",
         "a mortgage and a charge under this Act shall when registered as hereinbefore provided have effect as a security but shall not operate as a transfer of the land thereby mortgaged or charged.",
         TLA_PART_IV, "s. 106(1)",
         condition={"verification": "registered mortgage recorded as security, not transfer of land"}),
    cand(SV_TLA, tla_clauses, "s106", "tla_mortgage_default_notice_period_months",
         "and in case default be made in payment of the principal sum interest or annuity secured or any part thereof respectively or in the performance or observance of any covenant expressed in any mortgage or charge or hereby declared to be implied in any mortgage and such default be continued for one month or for such other period of time as may therein for that purpose be expressly fixed the mortgagee or annuitant or his transferees may serve on the mortgagor or grantor or his transferees notice in writing to pay the money owing on such mortgage or charge or to perform and observe the aforesaid covenants (as the case may be).",
         TLA_PART_IV, "s. 106(1)",
         operator="gte", value=1, unit="months", check_type="numeric_threshold",
         condition={"trigger": "default in payment or covenant observance", "default_period": "one month unless otherwise expressly fixed", "consequence": "mortgagee may serve written default notice"}),
    cand(SV_TLA, tla_clauses, "s61", "tla_no_survivorship_dealing_restriction",
         "In every case after such words shall have been signed by the Registrar whether under this or any preceding section it shall not be lawful for any persons other than the proprietors registered to transfer or otherwise deal with the property without the order of the Supreme Court or a judge thereof obtained on motion or petition or the order of the Commissioner.",
         TLA_PART_IV, "s. 61(3)", check_type="conditional",
         condition={"trigger": "words \"no survivorship\" entered on certificate of title", "verification": "dealing requires Supreme Court or Commissioner order if not by registered proprietors"}),
    cand(SV_TLA, tla_clauses, "s227", "tla_survivor_joint_proprietor_registration",
         "Upon the death of any person registered with any other person as joint proprietor of any land or of any lease or charge or as joint proprietor of any mortgage owned on a joint account in equity the Commissioner on the application of the person entitled and proof to his satisfaction of such events as aforesaid may direct the Registrar to register such applicant as the proprietor thereof.",
         TLA_PART_XIV, "s. 227",
         condition={"trigger": "death of joint proprietor", "verification": "survivorship application with proof of death"}),
    cand(SV_TLA, tla_clauses, "s219", "tla_transmission_application_evidence",
         "A devisee or person claiming any estate of freehold in possession or a power to appoint transfer or dispose of the same on a transmission may make application in writing to the Commissioner to be registered as proprietor thereof and shall produce the will or an office copy or probate of the will of the deceased proprietor or letters of administration with his will annexed or the letters of administration in case of intestacy or the settlement under which such applicant claims and shall afterwards furnish such other evidence as may be deemed necessary.",
         TLA_PART_XIV, "s. 219(1)",
         condition={"trigger": "transmission on death", "verification": "probate or letters of administration produced"}),
    cand(SV_TLA, tla_clauses, "s219", "tla_transmission_application_contents",
         "Such application shall state the nature of every interest held by any other person at law or equity in the land within the applicant's knowledge and that he verily believes himself to be entitled to the estate in or power over such land in respect to which he applies to be registered and shall also state the value of the property.",
         TLA_PART_XIV, "s. 219(2)",
         condition={"verification": "application states other interests and property value"}),
    cand(SV_TLA, tla_clauses, "s220", "tla_transmission_notice_min_days",
         "the Commissioner shall appoint a time not less than 14 days from the advertisement or the first of such advertisements if more than one upon or after which the Registrar shall unless a caveat shall be lodged forbidding the same register such applicant as the proprietor of such land or estate by entering in the Register the particulars of the transmission through which such applicant claims and by registering a certificate of title to the land or estate so transmitted.",
         TLA_PART_XIV, "s. 220(1)",
         operator="gte", value=14, unit="days", check_type="min_value",
         condition={"trigger": "advertisement of transmission application", "verification": "no caveat lodged forbidding registration"}),
]

reports["phase8_tla_extraction.json"] = {
    "source_version_id": SV_TLA,
    "source_pdf": "/app/data/raw-sources/transfer_of_land_act_1893.pdf",
    "instrument_section": "Parts IV, IVA, V, XIV (title & encumbrance provisions)",
    "tables_requested": ["s. 61", "s. 106", "s. 129B", "s. 129BA", "s. 136C",
                          "s. 137", "s. 138", "s. 138B", "s. 138C", "s. 138D",
                          "s. 139", "s. 140", "s. 141", "s. 219", "s. 220", "s. 227"],
    "candidates_extracted": len(tla_candidates),
    "warnings": [
        "Textual statute codified manually; applicable_r_codes and operator are null for boolean/verification rules by design.",
        "s. 121/122 20-year easement non-user provisions reviewed but not codified: operative mechanism is via s. 20 application and requires legal interpretation — flagged for future human review.",
    ],
    "candidates": tla_candidates,
}

print("Phase 8 candidates:", len(tla_candidates))

# =====================================================================
# PHASE 9 - Building Regulations 2012 (as at 17 Apr 2025)
# =====================================================================
br_clauses = {}
br_clause_defs = [
    ("r15B", "Modifications to AS 1926.1-2012 (s. 150)", "r. 15B",
     "For the purposes of these regulations, AS 1926.1-2012 as referenced in the Building Code is modified to delete clause 2.2.4 and insert: 2.2.4 Boundary barriers — A boundary barrier to a pool must satisfy either paragraph (a) or paragraph (b)."),
    ("r16", "Information to accompany application (s. 16)", "r. 16",
     "if the application is an application for a building permit to carry out builder work — (i) the registration number of the person as a building service contractor under the Building Services (Registration) Act 2011; or (ii) the number of the owner-builder approval given under the Building Services (Registration) Act 2011."),
    ("r18", "Grant of building permit (s. 20)", "r. 18",
     "For the purposes of section 20(1)(n), the following authorities under written laws are prescribed — (a) if the building work involves the construction or installation of any apparatus for the treatment of sewage as defined in the Health (Miscellaneous Provisions) Act 1911 section 3(1), the approval required under section 107(2)(a) or (b) of that Act; (b) if the building work is development as defined in the Planning and Development Act 2005 section 4, each approval required under that Act in relation to the work."),
    ("r36", "Display of occupancy permit details (s. 42(a))", "r. 36",
     "For the purposes of section 42(a) the following information about, or contained in, an occupancy permit must be displayed at or near the principal entrance to each part of the building to which the occupancy permit relates in a manner that is clearly visible to occupiers and other persons using the building."),
    ("r38", "Time for granting occupancy permit or building approval certificate (s. 59)", "r. 38",
     "For the purposes of section 59(1)(a)(i) the period for deciding whether or not to grant or modify an occupancy permit or grant a building approval certificate is 10 business days."),
    ("r41", "Building work for which building permit not required (s. 9(b))", "r. 41",
     "A building permit is not required for building work of a kind described in the Table in Schedule 4 clause 2."),
    ("r42", "Demolition work for which demolition permit not required (s. 10(c))", "r. 42",
     "A demolition permit is not required for the following demolition work — (a) demolition of a Class 10 building or incidental structure if — (i) the floor area of the building does not exceed 40 m2; and (ii) the demolition work will not adversely affect the safety and health of the occupants or other users of the building or incidental structure or of the public; and (iii) the building or incidental structure is not the subject of a protection order, heritage works permit, repair notice or repair order."),
    ("r43", "Buildings for which occupancy permit not required (s. 41(2))", "r. 43",
     "An occupancy permit is not required for any of the following — (a) a Class 1 or Class 10 building."),
    ("r50", "Barrier to private swimming pool", "r. 50",
     "Each owner and occupier of premises on which there is a private swimming pool containing water that is more than 300 mm deep must ensure that a pool barrier that restricts access to the pool and complies with the requirements of regulation 50A (and, if applicable, regulation 52) is installed or provided around the pool. Penalty for this subregulation: a fine of $5 000."),
    ("r50A", "Pool barrier requirements", "r. 50A",
     "Subject to subregulations (3) and (4), a pool barrier must comply with a Building Code pool barrier requirement that was in effect — (a) if a building permit applies to the construction of the pool — at or after the time the application for a building permit to construct the pool was made; or (b) otherwise — at or after the time the construction of the pool commenced."),
    ("r51", "Approvals by permit authority", "r. 51",
     "A permit authority may approve requirements alternative to the requirements of regulation 50A(4)(a)(i) if it is satisfied that the alternative requirements will restrict access to the pool as effectively as if there were compliance with AS 1926.1-1993."),
    ("r52", "Concessions for pre-November 2001 private swimming pools", "r. 52",
     "This regulation applies to a private swimming pool — (a) installed before 5 November 2001; or (b) installed on or after 5 November 2001 in accordance with plans, drawings and specifications submitted to the local government for approval before that day."),
    ("r53", "Inspection of barrier to private swimming pool", "r. 53",
     "The local government for the district in which a private swimming pool containing water that is more than 300 mm deep is located must arrange for an authorised person to inspect the barrier to the private swimming pool on the days and at the intervals described in subregulation (2), for the purpose of monitoring whether regulation 50(2) is being complied with."),
    ("r55", "Terms used (Smoke alarms)", "r. 55",
     "10 year life battery means a battery that is capable of powering a smoke alarm for at least 10 years without the alarm indicating the battery power is low."),
    ("r56", "Requirement to have smoke alarms or similar prior to transfer of dwelling", "r. 56",
     "If an owner of a dwelling transfers the ownership of it, the owner must, to the extent practicable, ensure that at the time of the transfer — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty for this subregulation: a fine of $5 000."),
    ("r57", "New owner must install smoke alarms or similar, and right to recover costs", "r. 57",
     "If an owner of a dwelling (the prior owner) transfers the ownership of it and fails to comply with regulation 56(1), the person to whom the ownership is transferred (the new owner) must, within the post-transfer period, ensure that — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty for this subregulation: a fine of $5 000."),
    ("r58", "Requirement to have smoke alarms or similar prior to tenancy", "r. 58",
     "The owner of the dwelling must, to the extent practicable, ensure that — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty for this subregulation: a fine of $5 000."),
    ("r59", "Requirement to have smoke alarms or similar prior to hire of dwelling", "r. 59",
     "The owner of a dwelling must not make the dwelling available for hire unless — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty: a fine of $5 000."),
    ("r60", "Requirements for smoke alarms", "r. 60",
     "The requirements for the purposes of regulations 56(1)(a), 57(1)(a), 58(a) and 59(a) are that — (a) the dwelling meets the requirements of the deemed-to-satisfy provisions about smoke alarms or smoke hazard management (other than the provisions about evacuation lighting) of the Building Code applicable at the time of installation of the alarms."),
    ("r61", "Local government approval of battery powered smoke alarms", "r. 61",
     "The local government of the district in which a dwelling is located may approve of the use, in the dwelling or a part of the dwelling, of a battery powered smoke alarm (rather than one that is connected to the mains power supply) if satisfied that, at the time of giving the approval, installing a smoke alarm connected to the mains power supply would involve — (a) a sufficient problem of a structural nature; or (b) a sufficient problem of any other nature, the cause of which is not within the control of the owner."),
    ("sch4_cl2", "Kinds of building work for which a building permit is not required", "Sch. 4 cl. 2",
     "Schedule 4 clause 2 Table — descriptions of building work for which a building permit is not required."),
]
for key, title, ref, text in br_clause_defs:
    br_clauses[key] = ensure_clause(SV_BR, key, title, ref, text)

BR_P8_POOLS = "Part 8 — Existing buildings, Division 2 — Private swimming pools"
BR_P8_SMOKE = "Part 8 — Existing buildings, Division 3 — Smoke alarms"
BR_P6 = "Part 6 — Circumstances in which building, demolition or occupancy permits not required"
BR_P3 = "Part 3 — Building and demolition permits"
BR_P5 = "Part 5 — Occupancy permits and building approval certificates"
BR_P2 = "Part 2 — General matters"
BR_SCH4 = "Schedule 4 — Building work that does not require building permit"

br_candidates = [
    # --- Private swimming pool barriers ---
    cand(SV_BR, br_clauses, "r50", "br_pool_barrier_required_water_depth_mm",
         "Each owner and occupier of premises on which there is a private swimming pool containing water that is more than 300 mm deep must ensure that a pool barrier that restricts access to the pool and complies with the requirements of regulation 50A (and, if applicable, regulation 52) is installed or provided around the pool. Penalty for this subregulation: a fine of $5 000.",
         BR_P8_POOLS, "r. 50(2)",
         operator="gt", value=300, unit="mm", check_type="numeric_threshold",
         condition={"element": "pool water depth", "consequence": "compliant pool barrier required", "penalty_aud": 5000}),
    cand(SV_BR, br_clauses, "r50A", "br_pool_barrier_restricts_access_from_building",
         "If all or part of a building (other than a Class 10 building) is within the area bounded by a pool barrier, that pool barrier or another pool barrier must restrict access to the pool from the building.",
         BR_P8_POOLS, "r. 50A(1)", check_type="conditional",
         condition={"trigger": "building (other than Class 10) within area bounded by pool barrier"}),
    cand(SV_BR, br_clauses, "r50A", "br_pool_barrier_building_code_compliance",
         "Subject to subregulations (3) and (4), a pool barrier must comply with a Building Code pool barrier requirement that was in effect — (a) if a building permit applies to the construction of the pool — at or after the time the application for a building permit to construct the pool was made; or (b) otherwise — at or after the time the construction of the pool commenced. Note for this subregulation: See also regulation 15B which modifies AS 1926.1-2012.",
         BR_P8_POOLS, "r. 50A(2)",
         condition={"verification": "barrier complies with Building Code pool barrier requirement in effect at/after permit application or construction commencement"}),
    cand(SV_BR, br_clauses, "r50A", "br_pool_barrier_performance_solution_must_be_approved",
         "For the purposes of subregulation (2), a performance solution cannot be used to comply with a Building Code pool barrier requirement unless the performance solution is an approved barrier solution.",
         BR_P8_POOLS, "r. 50A(3)",
         condition={"verification": "performance solution used only if approved barrier solution"}),
    cand(SV_BR, br_clauses, "r50A", "br_pool_pre_may_2016_alternative_compliance",
         "If the pool is a pre-May 2016 private swimming pool, the pool barrier need not comply with subregulation (2) if — (a) it is in accordance with — (i) the requirements of AS 1926.1-1993; or (ii) approved alternative requirements; and (b) any wall comprising part of the pool barrier has no means of access to the pool through a building other than — (i) a window that is in accordance with the requirements of AS 1926.1-1993; or (ii) an approved door.",
         BR_P8_POOLS, "r. 50A(4)", check_type="conditional",
         condition={"pool_era": "pre-May 2016 private swimming pool"}),
    cand(SV_BR, br_clauses, "r50A", "br_pool_boundary_fence_as1926_1993",
         "For the purposes of subregulation (4)(a), a boundary fence of the premises that is part of the pool barrier is in accordance with the requirements of clauses 2.3, 2.6 and 2.7 of AS 1926.1-1993 if all those requirements are satisfied in relation to either side of the fence.",
         BR_P8_POOLS, "r. 50A(5)", check_type="conditional",
         condition={"verification": "AS 1926.1-1993 clauses 2.3, 2.6, 2.7 satisfied on either side of boundary fence"}),
    cand(SV_BR, br_clauses, "r52", "br_pool_pre_nov_2001_concession",
         "For the purposes of regulation 50(2), the immediate surrounds of a private swimming pool to which this regulation applies may include any part of the premises on which the pool is located. The pool barrier required by regulation 50(2) may include a wall that contains a door permitting access to the pool through a building if that door satisfies the requirements of AS 1926.1-1993.",
         BR_P8_POOLS, "r. 52(2)-(3)", check_type="conditional",
         condition={"pool_era": "installed before 5 November 2001 (or per plans submitted before that day)"}),
    cand(SV_BR, br_clauses, "r53", "br_pool_inspection_initial_max_days",
         "if the local government has never arranged for an authorised person to inspect the barrier — a day that is no more than 30 days after the day on which the first of the following occurs — (i) the local government receives a notice of completion under section 33 stating that the building work in respect of the barrier or the private swimming pool is completed; (ii) the local government receives details of a notice of completion under section 7(2)(b) indicating that the building work in respect of the barrier or the private swimming pool is completed; (iii) the local government otherwise becomes aware that it has never arranged for an authorised person to inspect a barrier to the private swimming pool.",
         BR_P8_POOLS, "r. 53(2)(a)",
         operator="lte", value=30, unit="days", check_type="max_value",
         condition={"trigger": "local government becomes aware of completed uninspected pool barrier"}),
    cand(SV_BR, br_clauses, "r53", "br_pool_inspection_reinspection_max_days",
         "if the authorised person is not satisfied that regulation 50(2) is being complied with — on a day that is within 60 days after the day of the relevant inspection.",
         BR_P8_POOLS, "r. 53(2)(b)(i)",
         operator="lte", value=60, unit="days", check_type="max_value",
         condition={"trigger": "inspection finds r. 50(2) non-compliance", "note": "further inspections required until compliant"}),
    cand(SV_BR, br_clauses, "r53", "br_pool_inspection_routine_max_interval_years",
         "in any other case — on a day that is within 4 years after the day of the relevant inspection.",
         BR_P8_POOLS, "r. 53(2)(b)(ii)",
         operator="lte", value=4, unit="years", check_type="max_value",
         condition={"trigger": "routine pool barrier inspection cycle"}),
    cand(SV_BR, br_clauses, "r51", "br_pool_permit_authority_alternative_approval",
         "A permit authority may approve requirements alternative to the requirements of regulation 50A(4)(a)(i) if it is satisfied that the alternative requirements will restrict access to the pool as effectively as if there were compliance with AS 1926.1-1993.",
         BR_P8_POOLS, "r. 51(2)", check_type="conditional",
         condition={"verification": "alternative requirements approved by permit authority as equally effective"}),
    cand(SV_BR, br_clauses, "r51", "br_pool_approved_door_conditions",
         "A permit authority may approve a door for the purposes of regulation 50A(4)(b)(ii) if the door is in accordance with the requirements of AS 1926.l-1993 and — (a) in the opinion of the permit authority, a fence or barrier satisfying regulation 50A between the building and the private swimming pool would cause — (i) a significant problem of a structural nature; or (ii) a significant problem of any other nature, the cause of which is not within the control of the owner or occupier; or (b) the private swimming pool is totally enclosed by a building; or (c) in the opinion of the permit authority, a fence or barrier satisfying regulation 50A between the building and the private swimming pool would create a significant problem for a person with a disability who is resident at the premises and wishes to have access to the pool.",
         BR_P8_POOLS, "r. 51(3)", check_type="conditional",
         condition={"verification": "approved door per AS 1926.1-1993 plus permit authority satisfaction; young child residence must be considered (r. 51(4))"}),
    # --- AS 1926.1-2012 modifications (r. 15B) — boundary barriers ---
    cand(SV_BR, br_clauses, "r15B", "br_pool_boundary_barrier_inside_height_min_mm",
         "A boundary barrier satisfies this paragraph if — (i) it has a height on the inside of not less than 1800 mm.",
         BR_P2, "r. 15B(a), cl. 2.2.4(a)(i)",
         operator="gte", value=1800, unit="mm", check_type="min_value",
         condition={"barrier_type": "boundary barrier", "option": "paragraph (a)", "measured": "inside (pool side)"}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_boundary_barrier_ncz5_quadrant_radius_mm",
         "it has NCZ-5 formed as a quadrant of 900 mm radius down from the top of the inside of the barrier.",
         BR_P2, "r. 15B(a), cl. 2.2.4(a)(ii)",
         operator="eq", value=900, unit="mm", check_type="numeric_threshold",
         condition={"barrier_type": "boundary barrier", "zone": "NCZ-5 quadrant from top of inside of barrier"}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_ncz5_internal_barrier_top_rail_max_mm",
         "where the width of the top rail or surface of the internal barrier is not more than 50 mm wide at any point within NCZ 5 — the internal barrier intersects at an angle of between 45 and 135 degrees to the 1800 mm boundary barrier.",
         BR_P2, "r. 15B(a), cl. 2.2.4(a)(ii)(I)",
         operator="lte", value=50, unit="mm", check_type="max_value",
         condition={"zone": "NCZ 5", "consequence": "internal barrier may intersect at 45-135 degrees"}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_ncz5_internal_barrier_height_min_mm",
         "where the width of the top rail or surface of the internal barrier is greater than 50 mm at any point within NCZ 5 — the internal barrier has a height not less than 1800 mm extending not less than 900 mm from the intersection.",
         BR_P2, "r. 15B(a), cl. 2.2.4(a)(ii)(II)",
         operator="gte", value=1800, unit="mm", check_type="min_value",
         condition={"zone": "NCZ 5", "trigger": "internal barrier top rail greater than 50 mm wide", "extension_min_mm": 900}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_boundary_barrier_outside_height_min_mm",
         "A boundary barrier satisfies this paragraph if — (i) it has a height on the outside (the non-pool side) of not less than 1200 mm.",
         BR_P2, "r. 15B(a), cl. 2.2.4(b)(i)",
         operator="gte", value=1200, unit="mm", check_type="min_value",
         condition={"barrier_type": "boundary barrier", "option": "paragraph (b)", "measured": "outside (non-pool side)"}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_boundary_barrier_outside_clear_zone_mm",
         "within 500 mm of the outside of the boundary barrier there are no steps, retaining walls, objects or level changes that would reduce the height of the outside of the boundary barrier below 1200 mm.",
         BR_P2, "r. 15B(a), cl. 2.2.4(b)(ii)",
         operator="gte", value=500, unit="mm", check_type="numeric_threshold",
         condition={"zone": "within 500 mm of outside of boundary barrier", "requirement": "no steps, retaining walls, objects or level changes reducing effective height below 1200 mm"}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_boundary_barrier_ncz_requirements",
         "NCZ 1, 2, 3 and, if the boundary barrier has vertical openings of 10-100 mm in width, NCZ 4 (as described in clause 2.2.2) are present on the boundary barrier.",
         BR_P2, "r. 15B(a), cl. 2.2.4(b)(iii)", check_type="conditional",
         condition={"zones": "NCZ 1, 2, 3 always; NCZ 4 if vertical openings 10-100 mm"}),
    cand(SV_BR, br_clauses, "r15B", "br_pool_barrier_vertical_member_opening_max_mm",
         "is modified in clause 2.3.5(a) to insert after \"plane\": and vertical members are spaced to provide a clear opening of not more than 10 mm.",
         BR_P2, "r. 15B(b), cl. 2.3.5(a)",
         operator="lte", value=10, unit="mm", check_type="max_value",
         condition={"element": "clear opening between vertical members (modified AS 1926.1-2012 cl. 2.3.5(a); Figure 2.6 modified from 100 mm to 10 mm)"}),
    # --- Smoke alarms ---
    cand(SV_BR, br_clauses, "r56", "br_smoke_alarm_required_on_transfer",
         "If an owner of a dwelling transfers the ownership of it, the owner must, to the extent practicable, ensure that at the time of the transfer — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty for this subregulation: a fine of $5 000.",
         BR_P8_SMOKE, "r. 56(1)",
         condition={"trigger": "transfer of ownership of dwelling", "penalty_aud": 5000, "defence": "declaration of intended demolition given before transfer (r. 56(2))"}),
    cand(SV_BR, br_clauses, "r57", "br_smoke_alarm_new_owner_install_max_months",
         "the new owner must, within the post-transfer period, ensure that — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2) ... post-transfer period, in relation to a dwelling, means — (b) if the new owner did not give the prior owner a declaration of intended demolition for the dwelling before the time of the transfer — the period of 12 months beginning on the transfer day.",
         BR_P8_SMOKE, "r. 57(1), (1A)(b)",
         operator="lte", value=12, unit="months", check_type="max_value",
         condition={"trigger": "prior owner failed to comply with r. 56(1)", "penalty_aud": 5000}),
    cand(SV_BR, br_clauses, "r57", "br_smoke_alarm_new_owner_demolition_max_months",
         "post-transfer period, in relation to a dwelling, means — (a) if the new owner gave the prior owner a declaration of intended demolition for the dwelling before the time of the transfer — the period of 6 months beginning on the transfer day.",
         BR_P8_SMOKE, "r. 57(1A)(a)",
         operator="lte", value=6, unit="months", check_type="max_value",
         condition={"trigger": "declaration of intended demolition given before transfer"}),
    cand(SV_BR, br_clauses, "r58", "br_smoke_alarm_required_prior_to_tenancy",
         "The owner of the dwelling must, to the extent practicable, ensure that — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty for this subregulation: a fine of $5 000.",
         BR_P8_SMOKE, "r. 58(2)",
         condition={"trigger": "dwelling rented or made available for rent under residential tenancy agreement, or is/made available as short-term rental accommodation", "penalty_aud": 5000}),
    cand(SV_BR, br_clauses, "r59", "br_smoke_alarm_required_prior_to_hire",
         "The owner of a dwelling must not make the dwelling available for hire unless — (a) the dwelling has smoke alarms installed so that the dwelling and the alarms comply with the requirements of regulation 60(2); or (b) if an approved alternative building solution applies in relation to the dwelling — the solution is in effect. Penalty: a fine of $5 000.",
         BR_P8_SMOKE, "r. 59",
         condition={"trigger": "dwelling made available for hire", "penalty_aud": 5000}),
    cand(SV_BR, br_clauses, "r60", "br_smoke_alarm_building_code_dts_compliance",
         "the dwelling meets the requirements of the deemed-to-satisfy provisions about smoke alarms or smoke hazard management (other than the provisions about evacuation lighting) of the Building Code applicable at the time of installation of the alarms.",
         BR_P8_SMOKE, "r. 60(2)(a)",
         condition={"verification": "dwelling meets Building Code deemed-to-satisfy smoke alarm provisions applicable at time of installation"}),
    cand(SV_BR, br_clauses, "r60", "br_smoke_alarm_max_age_years",
         "each smoke alarm necessary to meet those requirements — (i) if an expiry date is provided on the alarm — has not reached that expiry date; or (ii) if no expiry date is provided on the alarm — was installed less than 10 years before the relevant day.",
         BR_P8_SMOKE, "r. 60(2)(b)",
         operator="lt", value=10, unit="years", check_type="max_value",
         condition={"element": "smoke alarm age at relevant day (where no expiry date provided)"}),
    cand(SV_BR, br_clauses, "r60", "br_smoke_alarm_working_order",
         "each smoke alarm referred to in paragraph (b) is in working order.",
         BR_P8_SMOKE, "r. 60(2)(c)",
         condition={"verification": "smoke alarm in working order"}),
    cand(SV_BR, br_clauses, "r60", "br_smoke_alarm_mains_power_connection",
         "if a smoke alarm referred to in paragraph (b) was, at the time of its installation, required to be connected to the mains power supply to meet those requirements — (i) the alarm is permanently connected to the mains power supply; or (ii) if the alarm is to be installed at a location in the dwelling where there is no hidden space in which to run the necessary electrical wiring and there is no appropriate alternative location — the alarm has a 10 year life battery that cannot be removed; or (iii) if, in relation to the alarm, the use of a battery powered smoke alarm has been approved under regulation 61 — the alarm has a 10 year life battery that cannot be removed.",
         BR_P8_SMOKE, "r. 60(2)(d)", check_type="conditional",
         condition={"verification": "mains-powered where required at installation; otherwise non-removable 10 year life battery"}),
    cand(SV_BR, br_clauses, "r55", "br_smoke_alarm_10_year_life_battery_definition",
         "10 year life battery means a battery that is capable of powering a smoke alarm for at least 10 years without the alarm indicating the battery power is low.",
         BR_P8_SMOKE, "r. 55(1)",
         operator="gte", value=10, unit="years", check_type="min_value",
         condition={"element": "10 year life battery capability"}),
    cand(SV_BR, br_clauses, "r60", "br_smoke_alarm_interconnection_exemption",
         "Despite subregulation (2)(a) a dwelling is not required to meet a provision of the Building Code applicable at the time of installation of the alarms that requires smoke alarms to be interconnected if — (a) a building licence for the construction, erection, assembly or placement of the dwelling was issued under the Local Government (Miscellaneous Provisions) Act 1960 before commencement day; or (b) a building permit for the construction, erection, assembly or placement of the dwelling was granted on an application for a building permit made before 1 May 2015; or (c) a building permit or a building licence was not required for the construction, erection, assembly or placement of the dwelling and the construction, erection, assembly or placement of the dwelling commenced before 1 May 2015.",
         BR_P8_SMOKE, "r. 60(4)", check_type="conditional",
         condition={"verification": "interconnection per Building Code unless pre-1 May 2015 exemption applies"}),
    cand(SV_BR, br_clauses, "r61", "br_smoke_alarm_battery_approval_grounds",
         "The local government of the district in which a dwelling is located may approve of the use, in the dwelling or a part of the dwelling, of a battery powered smoke alarm (rather than one that is connected to the mains power supply) if satisfied that, at the time of giving the approval, installing a smoke alarm connected to the mains power supply would involve — (a) a sufficient problem of a structural nature; or (b) a sufficient problem of any other nature, the cause of which is not within the control of the owner.",
         BR_P8_SMOKE, "r. 61(1)", check_type="conditional",
         condition={"verification": "local government approval for battery powered alarm"}),
    cand(SV_BR, br_clauses, "r61", "br_smoke_alarm_battery_approval_fee_max_aud",
         "An application for approval must be made in the manner and form approved by the local government, and must include or be accompanied by — (a) the plans and information required by the local government; and (b) the fee set by the local government, which cannot exceed $179.40.",
         BR_P8_SMOKE, "r. 61(3)",
         operator="lte", value=179.40, unit="AUD", check_type="max_value",
         condition={"element": "local government fee for battery powered smoke alarm approval"}),
    cand(SV_BR, br_clauses, "r61", "br_smoke_alarm_battery_approval_deemed_refusal_days",
         "The local government is to be taken to have refused approval if it has not made a decision whether to give approval within 35 days after the later of — (a) the day on which the person made the application for approval; or (b) the day on which the person complied with a, or the latest, request by the local government for further plans or information.",
         BR_P8_SMOKE, "r. 61(4)",
         operator="lte", value=35, unit="days", check_type="max_value",
         condition={"consequence": "deemed refusal if no decision within 35 days"}),
    # --- Building / demolition / occupancy permits ---
    cand(SV_BR, br_clauses, "r41", "br_building_permit_exemption_schedule4",
         "A building permit is not required for building work of a kind described in the Table in Schedule 4 clause 2.",
         BR_P6, "r. 41(3)", check_type="conditional",
         condition={"verification": "building work kind listed in Schedule 4 clause 2 Table"}),
    cand(SV_BR, br_clauses, "r42", "br_demolition_permit_exemption_class10_max_m2",
         "A demolition permit is not required for the following demolition work — (a) demolition of a Class 10 building or incidental structure if — (i) the floor area of the building does not exceed 40 m2; and (ii) the demolition work will not adversely affect the safety and health of the occupants or other users of the building or incidental structure or of the public; and (iii) the building or incidental structure is not the subject of a protection order, heritage works permit, repair notice or repair order.",
         BR_P6, "r. 42(a)",
         operator="lte", value=40, unit="m2", check_type="max_value",
         condition={"building_class": "Class 10", "additional_conditions": "no adverse safety/health effect; no protection order, heritage works permit, repair notice or repair order"}),
    cand(SV_BR, br_clauses, "r43", "br_occupancy_permit_not_required_class1_class10",
         "An occupancy permit is not required for any of the following — (a) a Class 1 or Class 10 building.",
         BR_P6, "r. 43(a)",
         condition={"building_class": ["Class 1", "Class 10"], "verification": "occupancy permit exemption"}),
    cand(SV_BR, br_clauses, "r38", "br_occupancy_permit_decision_max_business_days",
         "For the purposes of section 59(1)(a)(i) the period for deciding whether or not to grant or modify an occupancy permit or grant a building approval certificate is 10 business days.",
         BR_P5, "r. 38",
         operator="lte", value=10, unit="business_days", check_type="max_value",
         condition={"trigger": "application for occupancy permit or building approval certificate"}),
    cand(SV_BR, br_clauses, "r36", "br_occupancy_permit_display_required",
         "For the purposes of section 42(a) the following information about, or contained in, an occupancy permit must be displayed at or near the principal entrance to each part of the building to which the occupancy permit relates in a manner that is clearly visible to occupiers and other persons using the building — (a) the name or other description of the building; (b) the classification of the building; (c) the use authorised by the occupancy permit; (d) the name of the permit authority for the building.",
         BR_P5, "r. 36",
         condition={"verification": "occupancy permit details displayed at or near principal entrance"}),
    cand(SV_BR, br_clauses, "r16", "br_owner_builder_approval_number_required",
         "if the application is an application for a building permit to carry out builder work — (i) the registration number of the person as a building service contractor under the Building Services (Registration) Act 2011; or (ii) the number of the owner-builder approval given under the Building Services (Registration) Act 2011.",
         BR_P3, "r. 16(2)(c)",
         condition={"trigger": "building permit application for builder work", "verification": "builder registration number or owner-builder approval number accompanies application"}),
    cand(SV_BR, br_clauses, "r18", "br_building_permit_prerequisite_approvals",
         "For the purposes of section 20(1)(n), the following authorities under written laws are prescribed — (a) if the building work involves the construction or installation of any apparatus for the treatment of sewage as defined in the Health (Miscellaneous Provisions) Act 1911 section 3(1), the approval required under section 107(2)(a) or (b) of that Act; (b) if the building work is development as defined in the Planning and Development Act 2005 section 4, each approval required under that Act in relation to the work.",
         BR_P3, "r. 18(2)", check_type="conditional",
         condition={"verification": "health/sewage and planning approvals obtained before building permit grant where applicable"}),
    # --- Schedule 4 clause 2 exemption thresholds ---
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_class10a_floor_area_max_m2",
         "Construction, erection, assembly or placement of a freestanding Class 10a building that — (a) has a floor area not exceeding 10 m2.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 1(a)",
         operator="lte", value=10, unit="m2", check_type="max_value",
         condition={"exemption": "building permit not required", "building_class": "freestanding Class 10a", "also": "height no more than 2.4 m; not in wind region C or D (AS 1170.2)"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_class10a_height_max_m",
         "Construction, erection, assembly or placement of a freestanding Class 10a building that — (b) is no more than 2.4 m in height.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 1(b)",
         operator="lte", value=2.4, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "building_class": "freestanding Class 10a", "also": "floor area not exceeding 10 m2; not in wind region C or D (AS 1170.2)"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_fence_masonry_height_max_m",
         "the fence, screen or similar structure is, or is to be, located in a district in which there is no local law of a type referred to in paragraph (a) and the fence, screen or similar structure — (i) if constructed of masonry — is no more than 0.75 m in height.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 4(b)(i)",
         operator="lte", value=0.75, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "material": "masonry", "also": "not a fall prevention barrier; not in wind region C or D (AS 1170.2); no applicable LG s. 9.60 local law"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_fence_other_height_max_m",
         "if constructed of a material other than masonry — is no more than 1.8 m in height.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 4(b)(ii)",
         operator="lte", value=1.8, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "material": "other than masonry", "also": "not a fall prevention barrier; not in wind region C or D (AS 1170.2); no applicable LG s. 9.60 local law"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_antenna_attached_height_max_m",
         "if attached to a building — (i) is no more than 2 m in height above the highest point of attachment to the building; and (ii) will not affect the way in which the building complies with each building standard that applies to the building.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 5(b)",
         operator="lte", value=2, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "element": "mast, antenna or similar structure attached to building", "also": "not in wind region C or D (AS 1170.2)"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_antenna_freestanding_height_max_m",
         "if not attached to a building, is no more than 3 m in height.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 5(c)",
         operator="lte", value=3, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "element": "freestanding mast, antenna or similar structure", "also": "not in wind region C or D (AS 1170.2)"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_retaining_wall_height_max_m",
         "Construction, erection, assembly or placement of a retaining wall that — (a) retains ground no more than 0.5 m in height; and (b) is not associated with other building work or with the protection of land adjoining the land on which the retaining wall is located; and (c) is not work of a kind to which section 76, 77, 78 or 79 relates.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 6",
         operator="lte", value=0.5, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "element": "retained ground height"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_pergola_height_max_m",
         "Construction, erection, assembly or placement of a pergola associated with a Class 1 building that — (a) is no more than 2.4 m in height.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 7(a)",
         operator="lte", value=2.4, unit="m", check_type="max_value",
         condition={"exemption": "building permit not required", "element": "pergola associated with Class 1 building", "also": "covers area not exceeding 20 m2; not in wind region C or D (AS 1170.2)"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_pergola_area_max_m2",
         "Construction, erection, assembly or placement of a pergola associated with a Class 1 building that — (c) covers an area not exceeding 20 m2.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 7(c)",
         operator="lte", value=20, unit="m2", check_type="max_value",
         condition={"exemption": "building permit not required", "element": "pergola associated with Class 1 building", "also": "height no more than 2.4 m; not in wind region C or D (AS 1170.2)"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_water_tank_capacity_max_l",
         "Construction, erection, assembly or placement of a water storage tank with a capacity of 5 000 L or less.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 8",
         operator="lte", value=5000, unit="L", check_type="max_value",
         condition={"exemption": "building permit not required", "element": "water storage tank capacity"}),
    # --- needs human review items ---
    cand(SV_BR, br_clauses, "r41", "br_building_permit_exemption_district_areas",
         "A building permit is not required for the following building work — (a) building work for a Class 10 building or incidental structure that is located, or to be located, in a local government district specified in column 1 of the Table in the area specified for that district in column 2 of the Table; (b) building work for a building or incidental structure that is not a Class 10 building or incidental structure and that is located, or to be located, in a local government district specified in column 1 of the Table in the area (if any) specified for that district in column 3 of the Table.",
         BR_P6, "r. 41(1)-(2)", check_type="conditional", evaluable="needs_review",
         condition={"reason": "exemption depends on district-specific areas in Schedule 4 clause 1 Table; requires per-district spatial resolution"}),
    cand(SV_BR, br_clauses, "sch4_cl2", "br_exempt_evaporative_cooler_bushfire_conditions",
         "The installation of a roof mounted evaporative cooling unit on a building or incidental structure if — (a) the building or incidental structure is not located in a bush fire prone area; or (b) the building is a Class 4 to Class 9 building (other than a Class 9 vulnerable use building); or (c) the building or incidental structure is located in a bush fire prone area, the BAL for the building site is BAL LOW ... (d) ... the BAL for the building site is BAL-12.5, BAL-19 or BAL-29; (iii) the installation of the evaporative cooling unit complies with the requirements for roof penetration in respect of the building or incidental structure set out in AS 3959.",
         BR_SCH4, "Sch. 4 cl. 2 Table item 13", check_type="conditional", evaluable="needs_review",
         condition={"reason": "multi-branch BAL/building-class conditions require site BAL determination before evaluation"}),
]

reports["phase9_building_regs_extraction.json"] = {
    "source_version_id": SV_BR,
    "source_pdf": "/app/data/raw-sources/building_regs_2012.pdf",
    "instrument_section": "Parts 2, 3, 5, 6, 8 and Schedule 4 (safety & permit provisions)",
    "tables_requested": ["r. 15B", "r. 16", "r. 18", "r. 36", "r. 38", "r. 41",
                          "r. 42", "r. 43", "r. 50", "r. 50A", "r. 51", "r. 52",
                          "r. 53", "r. 55", "r. 56", "r. 57", "r. 58", "r. 59",
                          "r. 60", "r. 61", "Sch. 4 cl. 2"],
    "candidates_extracted": len(br_candidates),
    "warnings": [
        "Textual regulation codified manually; applicable_r_codes and operator are null for boolean/verification rules by design.",
        "RCD (residual current device) requirements: NO provision found anywhere in Building Regulations 2012 (as at 17 Apr 2025) — RCD obligations arise under electricity safety legislation, not this instrument. Gap reported, no rule invented.",
        "Photoelectric smoke alarm type: the term does not appear in this instrument; alarm type/location requirements are incorporated via the Building Code deemed-to-satisfy reference in r. 60(2)(a). Codified as such.",
        "Barrier height 1200mm: appears in this instrument only as the modified boundary-barrier outside height (r. 15B cl. 2.2.4(b)(i)); general 1200mm fence heights live in AS 1926.1-2012 as referenced by the Building Code, not in the regulation text.",
    ],
    "candidates": br_candidates,
}

print("Phase 9 candidates:", len(br_candidates))

# =====================================================================
# PHASE 11 - Strata Titles Act 1985 (as at 26 Jun 2025)
# =====================================================================
sta_clauses = {}
sta_clause_defs = [
    ("s91", "General duty", "s. 91",
     "A strata company must — (b) control and manage the common property for the benefit of all the owners of lots; and (c) keep in good and serviceable repair, properly maintain and, if necessary, renew and replace — (i) the common property, including the fittings, fixtures and lifts used in connection with the common property; and (ii) any personal property owned by the strata company, and to do so whether damage or deterioration arises from fair wear and tear, inherent defect or any other cause."),
    ("s97", "Required insurance", "s. 97",
     "A strata company must ensure that the following insurance is in place for the strata titles scheme — (a) all insurable assets of the scheme must be insured against fire, storm and tempest (excluding damage by sea, flood or erosion), lightning, explosion and earthquake — (i) to replacement value; or (ii) to replacement value up to, for an event of a specified kind, a maximum amount specified in the contract of insurance that is a reasonable limitation in the circumstances; and (b) the strata company must be insured against damage to property, death, bodily injury or illness for which the strata company could become liable in damages to an amount of not less than $10,000,000 or, if some other amount is determined under the regulations, that amount."),
    ("s100", "Administrative and reserve funds and contributions", "s. 100",
     "A strata company must — (a) establish a fund (an administrative fund) for administrative expenses that is sufficient in the opinion of the strata company for the control and management of the common property, for the payment of any premiums of insurance and the discharge of any other obligation of the strata company."),
    ("s102", "Budget", "s. 102",
     "The budget must be prepared — (a) taking into account, if applicable, the 10 year plan for the reserve fund; and (b) in accordance with any requirements set out in the regulations and the scheme by-laws. The strata company may, by ordinary resolution at its annual general meeting or at a subsequent general meeting, approve a budget with or without modification."),
    ("s123", "Resolutions", "s. 123",
     "A resolution of a strata company is a unanimous resolution if — (a) 14 days' notice of the terms of the proposed resolution is given to each member of the strata company before voting on the resolution opens; and (b) the vote attached to each lot in the scheme is cast in favour of the resolution."),
    ("s44", "Making of scheme by-laws", "s. 44",
     "Subject to this Act, a strata company may, by resolution of the strata company, make governance by-laws or conduct by-laws for the strata titles scheme (including by-laws that amend or repeal the by-laws it is taken to have made on registration of the scheme). The resolution to make by-laws must be — (a) for governance by-laws — a resolution without dissent; and (b) for conduct by-laws — a special resolution."),
    ("s45", "Application of scheme by-laws", "s. 45",
     "Each person to whom scheme by-laws apply must comply with the by-laws as if the by-laws were a deed (signed and sealed by each person to whom they apply) containing mutual covenants to observe and perform the matters set out in the by-laws."),
    ("s46", "Invalidity of scheme by-laws", "s. 46",
     "Scheme by-laws are invalid as follows — (a) to the extent that there is no power to make the by-laws; (b) to the extent that they are inconsistent with this Act or any other written law; (c) to the extent that they are inconsistent with a restricted use condition."),
]
for key, title, ref, text in sta_clause_defs:
    sta_clauses[key] = ensure_clause(SV_STA, key, title, ref, text)

STA_P8_FN = "Part 8 — Strata company, Division 1 — Functions"
STA_P8_PROC = "Part 8 — Strata company, Division 3 — Procedures"
STA_P4 = "Part 4 — Scheme documents, Division 4 — Scheme by-laws"

sta_candidates = [
    cand(SV_STA, sta_clauses, "s91", "sta_common_property_manage_and_repair",
         "A strata company must — (b) control and manage the common property for the benefit of all the owners of lots; and (c) keep in good and serviceable repair, properly maintain and, if necessary, renew and replace — (i) the common property, including the fittings, fixtures and lifts used in connection with the common property; and (ii) any personal property owned by the strata company, and to do so whether damage or deterioration arises from fair wear and tear, inherent defect or any other cause.",
         STA_P8_FN, "s. 91(1)",
         condition={"verification": "strata company controls, manages, repairs and maintains common property"}),
    cand(SV_STA, sta_clauses, "s97", "sta_insurance_replacement_value_assets",
         "all insurable assets of the scheme must be insured against fire, storm and tempest (excluding damage by sea, flood or erosion), lightning, explosion and earthquake — (i) to replacement value; or (ii) to replacement value up to, for an event of a specified kind, a maximum amount specified in the contract of insurance that is a reasonable limitation in the circumstances.",
         STA_P8_FN, "s. 97(1)(a)", check_type="categorical",
         condition={"verification": "insurable assets insured to replacement value against prescribed events"}),
    cand(SV_STA, sta_clauses, "s97", "sta_insurance_liability_min_aud",
         "the strata company must be insured against damage to property, death, bodily injury or illness for which the strata company could become liable in damages to an amount of not less than $10,000,000 or, if some other amount is determined under the regulations, that amount.",
         STA_P8_FN, "s. 97(1)(b)",
         operator="gte", value=10000000, unit="AUD", check_type="min_value",
         condition={"element": "strata company liability insurance amount"}),
    cand(SV_STA, sta_clauses, "s97", "sta_insurance_best_available_fallback",
         "However, if a strata company has taken all reasonably practicable steps available to it to obtain the required insurance but no insurer is willing to enter into a contract of insurance on reasonable terms that meets the requirements, the strata company must obtain whatever insurance it can obtain on reasonable terms that most closely meets the requirements.",
         STA_P8_FN, "s. 97(2)", check_type="conditional",
         condition={"trigger": "no insurer willing on reasonable terms", "verification": "all reasonably practicable steps taken"}),
    cand(SV_STA, sta_clauses, "s97", "sta_insurance_payout_applied_to_reinstatement",
         "Subject to subsection (6), if a strata company receives money from an insurer in the event of damage to or destruction of an insurable asset of the strata titles scheme, that money must be applied by the strata company in rebuilding, replacing, repairing or restoring the insurable asset so far as that may lawfully be done.",
         STA_P8_FN, "s. 97(5)",
         condition={"verification": "insurance proceeds applied to reinstatement of insurable asset"}),
    cand(SV_STA, sta_clauses, "s100", "sta_administrative_fund_required",
         "A strata company must — (a) establish a fund (an administrative fund) for administrative expenses that is sufficient in the opinion of the strata company for the control and management of the common property, for the payment of any premiums of insurance and the discharge of any other obligation of the strata company; and (b) determine the amounts to be raised for payment into the administrative fund.",
         STA_P8_FN, "s. 100(1)(a)-(b)",
         condition={"verification": "administrative fund established and sufficient"}),
    cand(SV_STA, sta_clauses, "s100", "sta_levies_proportional_to_unit_entitlement",
         "raise amounts so determined by levying contributions on owners of lots — (i) in proportion to the unit entitlements of their respective lots; or (ii) if the scheme by-laws provide for a different basis for levying contributions, in accordance with that basis.",
         STA_P8_FN, "s. 100(1)(c)", check_type="categorical",
         condition={"verification": "administrative fund contributions levied per unit entitlement unless by-laws provide different basis"}),
    cand(SV_STA, sta_clauses, "s100", "sta_reserve_fund_designated_company",
         "A strata company must, if it is a designated strata company, and may, in any other case — (a) establish a fund (a reserve fund) for the purpose of accumulating funds to meet contingent expenses, other than those of a routine nature, and other major expenses of the strata company likely to arise in the future.",
         STA_P8_FN, "s. 100(2)", check_type="conditional",
         condition={"verification": "reserve fund mandatory for designated strata company; optional otherwise"}),
    cand(SV_STA, sta_clauses, "s100", "sta_designated_strata_company_min_lots",
         "designated strata company means — (a) a strata company for a scheme with 10 or more lots; or (b) a strata company included in this definition by the regulations.",
         STA_P8_FN, "s. 100(7)",
         operator="gte", value=10, unit="lots", check_type="numeric_threshold",
         condition={"consequence": "reserve fund and 10 year plan mandatory (s. 100(2), (2A))"}),
    cand(SV_STA, sta_clauses, "s100", "sta_10_year_plan_content",
         "A designated strata company must ensure — (a) that there is a 10 year plan that sets out — (i) the common property and the personal property of the strata company that is anticipated to require maintenance, repair, renewal or replacement (other than of a routine nature) in the period covered by the plan; and (ii) the estimated costs for the maintenance, repairs, renewal or replacement; and (iii) other information required to be included by the regulations.",
         STA_P8_FN, "s. 100(2A)(a)",
         condition={"verification": "10 year plan exists with anticipated works and estimated costs"}),
    cand(SV_STA, sta_clauses, "s100", "sta_10_year_plan_revision_max_years",
         "that the 10 year plan is revised at least once in each 5 years and that, when revised, the plan is extended to cover the 10 years following the revision.",
         STA_P8_FN, "s. 100(2A)(b)",
         operator="lte", value=5, unit="years", check_type="max_value",
         condition={"element": "10 year plan revision interval", "consequence": "plan extended to cover 10 years following revision"}),
    cand(SV_STA, sta_clauses, "s100", "sta_fund_functions_by_resolution",
         "Except in so far as and to the extent that the scheme by-laws may empower the council of that company to exercise the functions in subsections (1)(a), (b) and (c) and (2), those functions must be performed by and in accordance with resolutions passed by the strata company.",
         STA_P8_FN, "s. 100(3)", check_type="conditional",
         condition={"verification": "fund determination and levy functions exercised by strata company resolution unless by-laws empower council"}),
    cand(SV_STA, sta_clauses, "s102", "sta_budget_considers_10_year_plan",
         "The budget must be prepared — (a) taking into account, if applicable, the 10 year plan for the reserve fund; and (b) in accordance with any requirements set out in the regulations and the scheme by-laws.",
         STA_P8_FN, "s. 102(2)",
         condition={"verification": "budget takes into account 10 year plan where applicable"}),
    cand(SV_STA, sta_clauses, "s102", "sta_budget_approved_ordinary_resolution",
         "The strata company may, by ordinary resolution at its annual general meeting or at a subsequent general meeting, approve a budget with or without modification. The strata company may, by ordinary resolution, vary its approved budget.",
         STA_P8_FN, "s. 102(3)-(4)", check_type="categorical",
         condition={"verification": "budget approved/varied by ordinary resolution"}),
    cand(SV_STA, sta_clauses, "s123", "sta_unanimous_resolution_definition",
         "A resolution of a strata company is a unanimous resolution if — (a) 14 days' notice of the terms of the proposed resolution is given to each member of the strata company before voting on the resolution opens; and (b) the vote attached to each lot in the scheme is cast in favour of the resolution.",
         STA_P8_PROC, "s. 123(1)", check_type="categorical",
         condition={"verification": "all lot votes cast in favour; 14 days' notice given"}),
    cand(SV_STA, sta_clauses, "s123", "sta_resolution_without_dissent_definition",
         "Subject to subsection (3), a resolution of a strata company is a resolution without dissent if — (a) 14 days' notice of the terms of the proposed resolution is given to each member of the strata company before voting on the resolution opens; and (b) no vote attached to a lot in the scheme is cast against the resolution. For a 2-lot scheme, a resolution is only to be regarded as a resolution without dissent if it is a unanimous resolution.",
         STA_P8_PROC, "s. 123(2)-(3)", check_type="categorical",
         condition={"verification": "no vote against; 2-lot scheme requires unanimity"}),
    cand(SV_STA, sta_clauses, "s123", "sta_special_resolution_votes_for_min_pct",
         "a resolution of a strata company is a special resolution if — (b) the votes in favour of the resolution equal — (i) when counted by number — not less than 50% of the number of lots in the scheme; and (ii) when counted by unit entitlements — not less than 50% of the unit entitlements of the lots in the scheme.",
         STA_P8_PROC, "s. 123(4)(b)",
         operator="gte", value=50, unit="percent", check_type="min_value",
         condition={"counted": "by number of lots AND by unit entitlements", "also": "14 days' notice (s. 123(4)(a)); 2-lot scheme requires unanimous (s. 123(5))"}),
    cand(SV_STA, sta_clauses, "s123", "sta_special_resolution_votes_against_max_pct",
         "the votes against the resolution equal — (i) when counted by number — less than 25% of the number of lots in the scheme; and (ii) when counted by unit entitlements — less than 25% of the unit entitlements of the lots in the scheme.",
         STA_P8_PROC, "s. 123(4)(c)",
         operator="lt", value=25, unit="percent", check_type="max_value",
         condition={"counted": "by number of lots AND by unit entitlements"}),
    cand(SV_STA, sta_clauses, "s123", "sta_resolution_notice_min_days",
         "14 days' notice of the terms of the proposed resolution is given to each member of the strata company before voting on the resolution opens.",
         STA_P8_PROC, "s. 123(1)(a), (2)(a), (4)(a)",
         operator="gte", value=14, unit="days", check_type="min_value",
         condition={"applies_to": ["unanimous resolution", "resolution without dissent", "special resolution"]}),
    cand(SV_STA, sta_clauses, "s123", "sta_small_scheme_special_resolution_counts",
         "For a 3, 4 or 5-lot scheme, a resolution of the strata company is a special resolution if — (b) the votes in favour of the resolution equal — (i) when counted by number — (I) for a 3-lot scheme — not less than 2; and (II) for a 4-lot scheme — not less than 3; and (III) for a 5-lot scheme — not less than 4; and (ii) when counted by unit entitlements — not less than 50% of the unit entitlements of the lots in the scheme.",
         STA_P8_PROC, "s. 123(6)", check_type="conditional",
         condition={"votes_for_min": {"3_lot_scheme": 2, "4_lot_scheme": 3, "5_lot_scheme": 4}, "unit_entitlements_for_min_pct": 50}),
    cand(SV_STA, sta_clauses, "s44", "sta_bylaws_resolution_thresholds",
         "The resolution to make by-laws must be — (a) for governance by-laws — a resolution without dissent; and (b) for conduct by-laws — a special resolution.",
         STA_P4, "s. 44(2)", check_type="categorical",
         condition={"governance_by_laws": "resolution without dissent", "conduct_by_laws": "special resolution"}),
    cand(SV_STA, sta_clauses, "s44", "sta_bylaws_approved_form",
         "Scheme by-laws must be in the approved form.",
         STA_P4, "s. 44(5)",
         condition={"verification": "scheme by-laws in approved form"}),
    cand(SV_STA, sta_clauses, "s45", "sta_bylaws_binding_as_deed",
         "Each person to whom scheme by-laws apply must comply with the by-laws as if the by-laws were a deed (signed and sealed by each person to whom they apply) containing mutual covenants to observe and perform the matters set out in the by-laws.",
         STA_P4, "s. 45(2)",
         condition={"verification": "by-laws bind strata company, members, occupiers and lessees"}),
    cand(SV_STA, sta_clauses, "s46", "sta_bylaws_invalidity_grounds",
         "Scheme by-laws are invalid as follows — (a) to the extent that there is no power to make the by-laws; (b) to the extent that they are inconsistent with this Act or any other written law; (c) to the extent that they are inconsistent with a restricted use condition.",
         STA_P4, "s. 46", check_type="conditional",
         condition={"verification": "by-law validity against power, written law consistency, restricted use conditions"}),
    # --- needs human review items ---
    cand(SV_STA, sta_clauses, "s102", "sta_unbudgeted_expenditure_cap",
         "A strata company must not make any expenditure that is not authorised by an approved budget except for expenditure as follows — (a) expenditure of an amount not exceeding, in a financial year, for each lot in the strata titles scheme — (i) the amount fixed by the strata company by special resolution; or (ii) if the strata company has not fixed the amount by special resolution, the amount fixed by the regulations.",
         STA_P8_FN, "s. 102(6)(a)", check_type="conditional", evaluable="needs_review",
         condition={"reason": "numeric cap fixed by special resolution or Strata Titles (General) Regulations — value not stated in the Act"}),
    cand(SV_STA, sta_clauses, "s102", "sta_common_property_expenditure_special_resolution_threshold",
         "If a budget or a variation of a budget provides for expenditure on common property under section 91(2) (other than expenditure on sustainability infrastructure) exceeding an amount determined under the regulations — (a) information regarding that expenditure must be provided to the members of the strata company as required by the regulations; and (b) the budget or variation must be approved by special resolution.",
         STA_P8_FN, "s. 102(5)", check_type="conditional", evaluable="needs_review",
         condition={"reason": "threshold amount determined under regulations, not stated in the Act"}),
]

reports["phase11_strata_extraction.json"] = {
    "source_version_id": SV_STA,
    "source_pdf": "/app/data/raw-sources/strata_titles_act_1985.pdf",
    "instrument_section": "Parts 4 and 8 (strata company duties, funds, insurance, by-laws, resolutions)",
    "tables_requested": ["s. 44", "s. 45", "s. 46", "s. 91", "s. 97",
                          "s. 100", "s. 102", "s. 123"],
    "candidates_extracted": len(sta_candidates),
    "warnings": [
        "Textual statute codified manually; applicable_r_codes and operator are null for boolean/verification rules by design.",
        "s. 102(5) and s. 102(6)(a) numeric thresholds are set by regulations/special resolution, not in the Act — codified as needs_human_review candidates.",
    ],
    "candidates": sta_candidates,
}

print("Phase 11 candidates:", len(sta_candidates))

# =====================================================================
# Write reports
# =====================================================================
conn.commit()
for name, report in reports.items():
    path = f"/app/reports/{name}"
    with open(path, "w") as f:
        json.dump(report, f, indent=2)
    print("wrote", path, "candidates:", report["candidates_extracted"])

conn.close()
print("DONE")
