"""Source library domain package for DraftCheck V3."""

from draftcheck.domain.sources.library import (
    InMemorySourceLibrary,
    InMemorySourceSearchService,
    default_embedding_config,
)
from draftcheck.domain.sources.models import (
    AnswerStatus,
    ArtifactKind,
    ArtifactSubjectType,
    ContentAddressedArtifact,
    EmbeddingConfig,
    LicenceStatus,
    SourceAnswer,
    SourceCitation,
    SourceChunk,
    SourceDocument,
    SourceError,
    SourceFreshness,
    SourceImportResult,
    SourceNotCitableError,
    SourceNotFoundError,
    SourceRefreshResult,
    SourceReview,
    SourceReviewStatus,
    SourceSearchHit,
    SourceVersion,
    content_addressed_path,
    sha256_hex,
)

__all__ = [
    "AnswerStatus",
    "ArtifactKind",
    "ArtifactSubjectType",
    "ContentAddressedArtifact",
    "EmbeddingConfig",
    "InMemorySourceLibrary",
    "InMemorySourceSearchService",
    "LicenceStatus",
    "SourceAnswer",
    "SourceChunk",
    "SourceCitation",
    "SourceDocument",
    "SourceError",
    "SourceFreshness",
    "SourceImportResult",
    "SourceNotCitableError",
    "SourceNotFoundError",
    "SourceRefreshResult",
    "SourceReview",
    "SourceReviewStatus",
    "SourceSearchHit",
    "SourceVersion",
    "content_addressed_path",
    "default_embedding_config",
    "sha256_hex",
]
